version: "3.8"
services:
  api:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"
      MONGODB_DB: "pitch_deck_data"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: